/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutVoiceAgentsRouteImport } from './routes/_layout/voice-agents'
import { Route as LayoutTemplatesRouteImport } from './routes/_layout/templates'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSequencesRouteImport } from './routes/_layout/sequences'
import { Route as LayoutOfferPacksRouteImport } from './routes/_layout/offer-packs'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutGovernanceRouteImport } from './routes/_layout/governance'
import { Route as LayoutControlsRouteImport } from './routes/_layout/controls'
import { Route as LayoutCampaignsRouteImport } from './routes/_layout/campaigns'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout/analytics'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVoiceAgentsRoute = LayoutVoiceAgentsRouteImport.update({
  id: '/voice-agents',
  path: '/voice-agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesRoute = LayoutTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSequencesRoute = LayoutSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOfferPacksRoute = LayoutOfferPacksRouteImport.update({
  id: '/offer-packs',
  path: '/offer-packs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGovernanceRoute = LayoutGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutControlsRoute = LayoutControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCampaignsRoute = LayoutCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/campaigns': typeof LayoutCampaignsRoute
  '/controls': typeof LayoutControlsRoute
  '/governance': typeof LayoutGovernanceRoute
  '/items': typeof LayoutItemsRoute
  '/offer-packs': typeof LayoutOfferPacksRoute
  '/sequences': typeof LayoutSequencesRoute
  '/settings': typeof LayoutSettingsRoute
  '/templates': typeof LayoutTemplatesRoute
  '/voice-agents': typeof LayoutVoiceAgentsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/campaigns': typeof LayoutCampaignsRoute
  '/controls': typeof LayoutControlsRoute
  '/governance': typeof LayoutGovernanceRoute
  '/items': typeof LayoutItemsRoute
  '/offer-packs': typeof LayoutOfferPacksRoute
  '/sequences': typeof LayoutSequencesRoute
  '/settings': typeof LayoutSettingsRoute
  '/templates': typeof LayoutTemplatesRoute
  '/voice-agents': typeof LayoutVoiceAgentsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/campaigns': typeof LayoutCampaignsRoute
  '/_layout/controls': typeof LayoutControlsRoute
  '/_layout/governance': typeof LayoutGovernanceRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/offer-packs': typeof LayoutOfferPacksRoute
  '/_layout/sequences': typeof LayoutSequencesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/templates': typeof LayoutTemplatesRoute
  '/_layout/voice-agents': typeof LayoutVoiceAgentsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/analytics'
    | '/campaigns'
    | '/controls'
    | '/governance'
    | '/items'
    | '/offer-packs'
    | '/sequences'
    | '/settings'
    | '/templates'
    | '/voice-agents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/analytics'
    | '/campaigns'
    | '/controls'
    | '/governance'
    | '/items'
    | '/offer-packs'
    | '/sequences'
    | '/settings'
    | '/templates'
    | '/voice-agents'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/analytics'
    | '/_layout/campaigns'
    | '/_layout/controls'
    | '/_layout/governance'
    | '/_layout/items'
    | '/_layout/offer-packs'
    | '/_layout/sequences'
    | '/_layout/settings'
    | '/_layout/templates'
    | '/_layout/voice-agents'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/voice-agents': {
      id: '/_layout/voice-agents'
      path: '/voice-agents'
      fullPath: '/voice-agents'
      preLoaderRoute: typeof LayoutVoiceAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates': {
      id: '/_layout/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof LayoutTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sequences': {
      id: '/_layout/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof LayoutSequencesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/offer-packs': {
      id: '/_layout/offer-packs'
      path: '/offer-packs'
      fullPath: '/offer-packs'
      preLoaderRoute: typeof LayoutOfferPacksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/governance': {
      id: '/_layout/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof LayoutGovernanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/controls': {
      id: '/_layout/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof LayoutControlsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/campaigns': {
      id: '/_layout/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof LayoutCampaignsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutCampaignsRoute: typeof LayoutCampaignsRoute
  LayoutControlsRoute: typeof LayoutControlsRoute
  LayoutGovernanceRoute: typeof LayoutGovernanceRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutOfferPacksRoute: typeof LayoutOfferPacksRoute
  LayoutSequencesRoute: typeof LayoutSequencesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTemplatesRoute: typeof LayoutTemplatesRoute
  LayoutVoiceAgentsRoute: typeof LayoutVoiceAgentsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutCampaignsRoute: LayoutCampaignsRoute,
  LayoutControlsRoute: LayoutControlsRoute,
  LayoutGovernanceRoute: LayoutGovernanceRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutOfferPacksRoute: LayoutOfferPacksRoute,
  LayoutSequencesRoute: LayoutSequencesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTemplatesRoute: LayoutTemplatesRoute,
  LayoutVoiceAgentsRoute: LayoutVoiceAgentsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
