/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutVoiceAgentsRouteImport } from './routes/_layout/voice-agents'
import { Route as LayoutTemplatesRouteImport } from './routes/_layout/templates'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSequencesRouteImport } from './routes/_layout/sequences'
import { Route as LayoutReportingRouteImport } from './routes/_layout/reporting'
import { Route as LayoutProspectingRouteImport } from './routes/_layout/prospecting'
import { Route as LayoutOfferPacksRouteImport } from './routes/_layout/offer-packs'
import { Route as LayoutGovernanceRouteImport } from './routes/_layout/governance'
import { Route as LayoutControlsRouteImport } from './routes/_layout/controls'
import { Route as LayoutContactsRouteImport } from './routes/_layout/contacts'
import { Route as LayoutChatbotRouteImport } from './routes/_layout/chatbot'
import { Route as LayoutCampaignsRouteImport } from './routes/_layout/campaigns'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout/analytics'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSettingsProvidersRouteImport } from './routes/_layout/settings.providers'
import { Route as LayoutChatbotSettingsRouteImport } from './routes/_layout/chatbot.settings'
import { Route as LayoutChatbotKnowledgeBaseRouteImport } from './routes/_layout/chatbot.knowledge-base'
import { Route as LayoutChatbotInboxRouteImport } from './routes/_layout/chatbot.inbox'
import { Route as LayoutChatbotChannelsRouteImport } from './routes/_layout/chatbot.channels'
import { Route as LayoutChatbotAnalyticsRouteImport } from './routes/_layout/chatbot.analytics'
import { Route as LayoutChatbotInboxThreadIdRouteImport } from './routes/_layout/chatbot.inbox.$threadId'
import { Route as LayoutAdminChatbotDeadLettersRouteImport } from './routes/_layout/admin.chatbot.dead-letters'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVoiceAgentsRoute = LayoutVoiceAgentsRouteImport.update({
  id: '/voice-agents',
  path: '/voice-agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesRoute = LayoutTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSequencesRoute = LayoutSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportingRoute = LayoutReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProspectingRoute = LayoutProspectingRouteImport.update({
  id: '/prospecting',
  path: '/prospecting',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOfferPacksRoute = LayoutOfferPacksRouteImport.update({
  id: '/offer-packs',
  path: '/offer-packs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGovernanceRoute = LayoutGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutControlsRoute = LayoutControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactsRoute = LayoutContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatbotRoute = LayoutChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCampaignsRoute = LayoutCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsProvidersRoute = LayoutSettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutChatbotSettingsRoute = LayoutChatbotSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutChatbotRoute,
} as any)
const LayoutChatbotKnowledgeBaseRoute =
  LayoutChatbotKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => LayoutChatbotRoute,
  } as any)
const LayoutChatbotInboxRoute = LayoutChatbotInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => LayoutChatbotRoute,
} as any)
const LayoutChatbotChannelsRoute = LayoutChatbotChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => LayoutChatbotRoute,
} as any)
const LayoutChatbotAnalyticsRoute = LayoutChatbotAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutChatbotRoute,
} as any)
const LayoutChatbotInboxThreadIdRoute =
  LayoutChatbotInboxThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => LayoutChatbotInboxRoute,
  } as any)
const LayoutAdminChatbotDeadLettersRoute =
  LayoutAdminChatbotDeadLettersRouteImport.update({
    id: '/chatbot/dead-letters',
    path: '/chatbot/dead-letters',
    getParentRoute: () => LayoutAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/analytics': typeof LayoutAnalyticsRoute
  '/campaigns': typeof LayoutCampaignsRoute
  '/chatbot': typeof LayoutChatbotRouteWithChildren
  '/contacts': typeof LayoutContactsRoute
  '/controls': typeof LayoutControlsRoute
  '/governance': typeof LayoutGovernanceRoute
  '/offer-packs': typeof LayoutOfferPacksRoute
  '/prospecting': typeof LayoutProspectingRoute
  '/reporting': typeof LayoutReportingRoute
  '/sequences': typeof LayoutSequencesRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/templates': typeof LayoutTemplatesRoute
  '/voice-agents': typeof LayoutVoiceAgentsRoute
  '/chatbot/analytics': typeof LayoutChatbotAnalyticsRoute
  '/chatbot/channels': typeof LayoutChatbotChannelsRoute
  '/chatbot/inbox': typeof LayoutChatbotInboxRouteWithChildren
  '/chatbot/knowledge-base': typeof LayoutChatbotKnowledgeBaseRoute
  '/chatbot/settings': typeof LayoutChatbotSettingsRoute
  '/settings/providers': typeof LayoutSettingsProvidersRoute
  '/admin/chatbot/dead-letters': typeof LayoutAdminChatbotDeadLettersRoute
  '/chatbot/inbox/$threadId': typeof LayoutChatbotInboxThreadIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/analytics': typeof LayoutAnalyticsRoute
  '/campaigns': typeof LayoutCampaignsRoute
  '/chatbot': typeof LayoutChatbotRouteWithChildren
  '/contacts': typeof LayoutContactsRoute
  '/controls': typeof LayoutControlsRoute
  '/governance': typeof LayoutGovernanceRoute
  '/offer-packs': typeof LayoutOfferPacksRoute
  '/prospecting': typeof LayoutProspectingRoute
  '/reporting': typeof LayoutReportingRoute
  '/sequences': typeof LayoutSequencesRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/templates': typeof LayoutTemplatesRoute
  '/voice-agents': typeof LayoutVoiceAgentsRoute
  '/': typeof LayoutIndexRoute
  '/chatbot/analytics': typeof LayoutChatbotAnalyticsRoute
  '/chatbot/channels': typeof LayoutChatbotChannelsRoute
  '/chatbot/inbox': typeof LayoutChatbotInboxRouteWithChildren
  '/chatbot/knowledge-base': typeof LayoutChatbotKnowledgeBaseRoute
  '/chatbot/settings': typeof LayoutChatbotSettingsRoute
  '/settings/providers': typeof LayoutSettingsProvidersRoute
  '/admin/chatbot/dead-letters': typeof LayoutAdminChatbotDeadLettersRoute
  '/chatbot/inbox/$threadId': typeof LayoutChatbotInboxThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/campaigns': typeof LayoutCampaignsRoute
  '/_layout/chatbot': typeof LayoutChatbotRouteWithChildren
  '/_layout/contacts': typeof LayoutContactsRoute
  '/_layout/controls': typeof LayoutControlsRoute
  '/_layout/governance': typeof LayoutGovernanceRoute
  '/_layout/offer-packs': typeof LayoutOfferPacksRoute
  '/_layout/prospecting': typeof LayoutProspectingRoute
  '/_layout/reporting': typeof LayoutReportingRoute
  '/_layout/sequences': typeof LayoutSequencesRoute
  '/_layout/settings': typeof LayoutSettingsRouteWithChildren
  '/_layout/templates': typeof LayoutTemplatesRoute
  '/_layout/voice-agents': typeof LayoutVoiceAgentsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/chatbot/analytics': typeof LayoutChatbotAnalyticsRoute
  '/_layout/chatbot/channels': typeof LayoutChatbotChannelsRoute
  '/_layout/chatbot/inbox': typeof LayoutChatbotInboxRouteWithChildren
  '/_layout/chatbot/knowledge-base': typeof LayoutChatbotKnowledgeBaseRoute
  '/_layout/chatbot/settings': typeof LayoutChatbotSettingsRoute
  '/_layout/settings/providers': typeof LayoutSettingsProvidersRoute
  '/_layout/admin/chatbot/dead-letters': typeof LayoutAdminChatbotDeadLettersRoute
  '/_layout/chatbot/inbox/$threadId': typeof LayoutChatbotInboxThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/analytics'
    | '/campaigns'
    | '/chatbot'
    | '/contacts'
    | '/controls'
    | '/governance'
    | '/offer-packs'
    | '/prospecting'
    | '/reporting'
    | '/sequences'
    | '/settings'
    | '/templates'
    | '/voice-agents'
    | '/chatbot/analytics'
    | '/chatbot/channels'
    | '/chatbot/inbox'
    | '/chatbot/knowledge-base'
    | '/chatbot/settings'
    | '/settings/providers'
    | '/admin/chatbot/dead-letters'
    | '/chatbot/inbox/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/analytics'
    | '/campaigns'
    | '/chatbot'
    | '/contacts'
    | '/controls'
    | '/governance'
    | '/offer-packs'
    | '/prospecting'
    | '/reporting'
    | '/sequences'
    | '/settings'
    | '/templates'
    | '/voice-agents'
    | '/'
    | '/chatbot/analytics'
    | '/chatbot/channels'
    | '/chatbot/inbox'
    | '/chatbot/knowledge-base'
    | '/chatbot/settings'
    | '/settings/providers'
    | '/admin/chatbot/dead-letters'
    | '/chatbot/inbox/$threadId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/analytics'
    | '/_layout/campaigns'
    | '/_layout/chatbot'
    | '/_layout/contacts'
    | '/_layout/controls'
    | '/_layout/governance'
    | '/_layout/offer-packs'
    | '/_layout/prospecting'
    | '/_layout/reporting'
    | '/_layout/sequences'
    | '/_layout/settings'
    | '/_layout/templates'
    | '/_layout/voice-agents'
    | '/_layout/'
    | '/_layout/chatbot/analytics'
    | '/_layout/chatbot/channels'
    | '/_layout/chatbot/inbox'
    | '/_layout/chatbot/knowledge-base'
    | '/_layout/chatbot/settings'
    | '/_layout/settings/providers'
    | '/_layout/admin/chatbot/dead-letters'
    | '/_layout/chatbot/inbox/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/voice-agents': {
      id: '/_layout/voice-agents'
      path: '/voice-agents'
      fullPath: '/voice-agents'
      preLoaderRoute: typeof LayoutVoiceAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates': {
      id: '/_layout/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof LayoutTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sequences': {
      id: '/_layout/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof LayoutSequencesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reporting': {
      id: '/_layout/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof LayoutReportingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/prospecting': {
      id: '/_layout/prospecting'
      path: '/prospecting'
      fullPath: '/prospecting'
      preLoaderRoute: typeof LayoutProspectingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/offer-packs': {
      id: '/_layout/offer-packs'
      path: '/offer-packs'
      fullPath: '/offer-packs'
      preLoaderRoute: typeof LayoutOfferPacksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/governance': {
      id: '/_layout/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof LayoutGovernanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/controls': {
      id: '/_layout/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof LayoutControlsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contacts': {
      id: '/_layout/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof LayoutContactsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chatbot': {
      id: '/_layout/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof LayoutChatbotRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/campaigns': {
      id: '/_layout/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof LayoutCampaignsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/providers': {
      id: '/_layout/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof LayoutSettingsProvidersRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/chatbot/settings': {
      id: '/_layout/chatbot/settings'
      path: '/settings'
      fullPath: '/chatbot/settings'
      preLoaderRoute: typeof LayoutChatbotSettingsRouteImport
      parentRoute: typeof LayoutChatbotRoute
    }
    '/_layout/chatbot/knowledge-base': {
      id: '/_layout/chatbot/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/chatbot/knowledge-base'
      preLoaderRoute: typeof LayoutChatbotKnowledgeBaseRouteImport
      parentRoute: typeof LayoutChatbotRoute
    }
    '/_layout/chatbot/inbox': {
      id: '/_layout/chatbot/inbox'
      path: '/inbox'
      fullPath: '/chatbot/inbox'
      preLoaderRoute: typeof LayoutChatbotInboxRouteImport
      parentRoute: typeof LayoutChatbotRoute
    }
    '/_layout/chatbot/channels': {
      id: '/_layout/chatbot/channels'
      path: '/channels'
      fullPath: '/chatbot/channels'
      preLoaderRoute: typeof LayoutChatbotChannelsRouteImport
      parentRoute: typeof LayoutChatbotRoute
    }
    '/_layout/chatbot/analytics': {
      id: '/_layout/chatbot/analytics'
      path: '/analytics'
      fullPath: '/chatbot/analytics'
      preLoaderRoute: typeof LayoutChatbotAnalyticsRouteImport
      parentRoute: typeof LayoutChatbotRoute
    }
    '/_layout/chatbot/inbox/$threadId': {
      id: '/_layout/chatbot/inbox/$threadId'
      path: '/$threadId'
      fullPath: '/chatbot/inbox/$threadId'
      preLoaderRoute: typeof LayoutChatbotInboxThreadIdRouteImport
      parentRoute: typeof LayoutChatbotInboxRoute
    }
    '/_layout/admin/chatbot/dead-letters': {
      id: '/_layout/admin/chatbot/dead-letters'
      path: '/chatbot/dead-letters'
      fullPath: '/admin/chatbot/dead-letters'
      preLoaderRoute: typeof LayoutAdminChatbotDeadLettersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminChatbotDeadLettersRoute: typeof LayoutAdminChatbotDeadLettersRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminChatbotDeadLettersRoute: LayoutAdminChatbotDeadLettersRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutChatbotInboxRouteChildren {
  LayoutChatbotInboxThreadIdRoute: typeof LayoutChatbotInboxThreadIdRoute
}

const LayoutChatbotInboxRouteChildren: LayoutChatbotInboxRouteChildren = {
  LayoutChatbotInboxThreadIdRoute: LayoutChatbotInboxThreadIdRoute,
}

const LayoutChatbotInboxRouteWithChildren =
  LayoutChatbotInboxRoute._addFileChildren(LayoutChatbotInboxRouteChildren)

interface LayoutChatbotRouteChildren {
  LayoutChatbotAnalyticsRoute: typeof LayoutChatbotAnalyticsRoute
  LayoutChatbotChannelsRoute: typeof LayoutChatbotChannelsRoute
  LayoutChatbotInboxRoute: typeof LayoutChatbotInboxRouteWithChildren
  LayoutChatbotKnowledgeBaseRoute: typeof LayoutChatbotKnowledgeBaseRoute
  LayoutChatbotSettingsRoute: typeof LayoutChatbotSettingsRoute
}

const LayoutChatbotRouteChildren: LayoutChatbotRouteChildren = {
  LayoutChatbotAnalyticsRoute: LayoutChatbotAnalyticsRoute,
  LayoutChatbotChannelsRoute: LayoutChatbotChannelsRoute,
  LayoutChatbotInboxRoute: LayoutChatbotInboxRouteWithChildren,
  LayoutChatbotKnowledgeBaseRoute: LayoutChatbotKnowledgeBaseRoute,
  LayoutChatbotSettingsRoute: LayoutChatbotSettingsRoute,
}

const LayoutChatbotRouteWithChildren = LayoutChatbotRoute._addFileChildren(
  LayoutChatbotRouteChildren,
)

interface LayoutSettingsRouteChildren {
  LayoutSettingsProvidersRoute: typeof LayoutSettingsProvidersRoute
}

const LayoutSettingsRouteChildren: LayoutSettingsRouteChildren = {
  LayoutSettingsProvidersRoute: LayoutSettingsProvidersRoute,
}

const LayoutSettingsRouteWithChildren = LayoutSettingsRoute._addFileChildren(
  LayoutSettingsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutCampaignsRoute: typeof LayoutCampaignsRoute
  LayoutChatbotRoute: typeof LayoutChatbotRouteWithChildren
  LayoutContactsRoute: typeof LayoutContactsRoute
  LayoutControlsRoute: typeof LayoutControlsRoute
  LayoutGovernanceRoute: typeof LayoutGovernanceRoute
  LayoutOfferPacksRoute: typeof LayoutOfferPacksRoute
  LayoutProspectingRoute: typeof LayoutProspectingRoute
  LayoutReportingRoute: typeof LayoutReportingRoute
  LayoutSequencesRoute: typeof LayoutSequencesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRouteWithChildren
  LayoutTemplatesRoute: typeof LayoutTemplatesRoute
  LayoutVoiceAgentsRoute: typeof LayoutVoiceAgentsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutCampaignsRoute: LayoutCampaignsRoute,
  LayoutChatbotRoute: LayoutChatbotRouteWithChildren,
  LayoutContactsRoute: LayoutContactsRoute,
  LayoutControlsRoute: LayoutControlsRoute,
  LayoutGovernanceRoute: LayoutGovernanceRoute,
  LayoutOfferPacksRoute: LayoutOfferPacksRoute,
  LayoutProspectingRoute: LayoutProspectingRoute,
  LayoutReportingRoute: LayoutReportingRoute,
  LayoutSequencesRoute: LayoutSequencesRoute,
  LayoutSettingsRoute: LayoutSettingsRouteWithChildren,
  LayoutTemplatesRoute: LayoutTemplatesRoute,
  LayoutVoiceAgentsRoute: LayoutVoiceAgentsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
